---
- name: Run apt update and upgrade
  ansible.builtin.apt:
    state: present
    update_cache: yes
    upgrade: dist

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: yes

- name: Check if unattended-upgrades service is running
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
    enabled: yes 

- name: Reconfigure dpkg
  ansible.builtin.shell:
    dpkg-reconfigure -pmedium unattended-upgrades

- name: Configure sshd - no root and password login
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" } 

- name: Restart ssh to apply changes
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Install uncomplicated firewall (ufw)
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Check if ufw service is running
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: yes      
