---
- name: Run apt update and upgrade
  ansible.builtin.apt:
    state: present
    update_cache: yes
    upgrade: dist

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: yes

- name: Reconfigure dpkg
  ansible.builtin.shell:
    dpkg-reconfigure -pmedium unattended-upgrades

- name: Configure sshd - no root and password login
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regex: "^(#)?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
  loop:
    - { key: "PermitRootLogin", value: "no" }
    - { key: "PasswordAuthentication", value: "no" } 

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Install uncomplicated firewall (ufw)
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Check if ufw is started
  ansible.builtin.service:
    name: ufw
    state: started
    enabled: yes      

- name: Inform for next steps
  ansible.builtin.debug:
    msg: 
    - "Security setup completed"
    - "Modify ansible 'hosts' file by adding {{ server_username }} and his key path"
    - "Create new entry in ~/.ssh/config file for user {{ server_username }}"
    - "Change permission of {{ server_username }}_key to 600 and {{ server_username }}_key.pub to 644"