app:
  image_name: "{{ php_application.image_name }}"
  image_version: 1.0
  container_name: "{{ php_application.image_name }}"
  docker_port: 80
  vm_port: 80
  volume:
    name: "{{ php_application.image_name }}"
    path: "{{ php_application.mount_location }}"
  envs:
    db_host: db
    db_user: root
    db_name: "{{ db.envs.mysql_database }}"
    db_pass: "{{ secret_vars.encrypted_db_pass }}"
db:
  image_name: mysql
  image_version: 5.7
  volume:
    name: db_data
    path: /var/lib/mysql
  envs:
    mysql_root_password: "{{ secret_vars.encrypted_db_pass }}"
    mysql_database: telelabp_DB
